
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: national-transfer-microservice-sirone